name: Validate Mods

on:
  pull_request:
    paths:
      - 'mods.json'
  push:
    branches:
      - main
    paths:
      - 'mods.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install ajv ajv-formats

      - name: Validate mods.json Format
        run: |
          npx ajv validate -s mods.schema.json -d mods.json --spec=draft2019 --strict=false

      - name: Validate New Mod Repository
        run: |
          node .github/scripts/validate-repos.js
